GET http://localhost:8090
####

GET http://localhost:8090/user
###

GET http://localhost:8090/user/1
###

POST http://localhost:8090/user
Accept: 'application/json'
Content-Type: 'application/json

{
    "firstname":"Itay",
    "lastname":"Zemah"
}
###